version: '3.7'

services:
  nginx:
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
    volumes:
      - ${WWW_DIR}:/www:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw

  php:
    build:
      context: ./services/php
      args:
        PHP_VERSION: ${PHP_VERSION}-fpm-alpine
    volumes:
      - ${WWW_DIR}:/www:rw

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
