version: '3.7'

services:
  nginx:
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}-alpine
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
    volumes:
      - ${WWW_DIR}:/www:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    networks:
      - default

  php:
    build:
      context: ./services/php
      args:
        PHP_VERSION: ${PHP_VERSION}-fpm
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
    volumes:
      - ${WWW_DIR}:/www:rw
      - ${PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php:rw
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw
      - ${MYSQL_LOG_DIR}:/var/log/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - default

  redis:
    image: redis:${REDIS_VERSION}-alpine
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis/redis.conf:ro
      - ${REDIS_DATA_DIR}:/var/data/redis:rw
      - ${REDIS_LOG_DIR}:/var/log/redis:rw
    entrypoint: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      - default

networks:
  default:
